config/routes.rb
Rails.application.routes.draw do
  
  root 'schools#index'
  resources :schools 

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :activities
  validates_presence_of :name
  
  def admission 
    if self.students < 5000
      "Accepted"
    else
      "Denied"
    end   
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :school, except: [:index, :new, :create]

  def index
    @schools = School.all 
  end

  def show
  end

  def new
    @school = School.new 
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to schools_path
    else
      render :new
    end   
  end

  def edit
  end

  def update
    if @school.update(school_params)
      redirect_to schools_path
    else
      render :edit
    end 
  end

  def destroy
    @school.destroy
    redirect_to schools_path
  end 

  private
    def school_params
      params.require(:school).permit(:name, :location, :students)
    end

    def school
      @school = School.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schoolapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<div class='container'>
  <%= form_for(@school) do |f| %>
    <% if @school.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@school.errors.count, "error") %> prohibited  this school from being saved:</h2>
  
        <ul>
        <% @school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
   
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :students %><br>
      <%= f.number_field :students %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @schools.blank? %>
      <h1>No Schools</h1>
    <% end %>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.location %></td>
        <td><%= school.students %></td>
        <td><%= link_to 'Show', School %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1 class='center'>-Add New School-</h1>
<br />
<hr />

<%= render 'form' %>
<br />
<br />
<div class='container'>
<%= link_to 'Back', schools_path %>
</div>

app/views/schools/show.html.erb
<h1>Schools#show</h1>
<p>Find me in app/views/schools/show.html.erb</p>